//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectDB_Udabol.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class CLIENTES
    {
        [Display(Name ="#")]
        public int Id_Cliente { get; set; }
        [Display(Name = "Cedula")]
        public string Cedula { get; set; }
        [Display(Name = "Nombre")]
        public string Nombre { get; set; }
        [Display(Name = "Apellido Paterno")]
        public string Apellido_Paterno { get; set; }
        [Display(Name = "Apellido Materno")]
        public string Apellido_Materno { get; set; }
        [Display(Name = "Correo Electronico")]
        public string Correo { get; set; }
        [Display(Name = "Direccion")]
        public string Direccion { get; set; }
    }
}
